acquire_rates:
  BASE_URL: https://api.exchangeratesapi.io/history
  START_DATE: 2017-05-30
  END_DATE: 2019-05-30
  RAW_DATA_LOCATION: data/raw/raw_exchange_rates.json
  S3_LOCATION: nw-surabhiseth-s3
  S3_FILE_NAME: raw_exchange_rates.txt
train_model:
  DOWNLOAD_LOCATION: data/raw/exchange_rates_dl.json
  FORECAST_PERIOD: 7
  ARIMA_models:
    P:
      - 0
      - 0
      - 1
      - 0
      - 1
      - 1
      - 2
      - 0
      - 0
      - 2
      - 2
      - 0
      - 1
    D:
      - 0
      - 1
      - 0
      - 1
      - 0
      - 1
      - 0
      - 2
      - 0
      - 1
      - 0
      - 2
      - 0
    Q:
      - 1
      - 0
      - 0
      - 1
      - 1
      - 0
      - 0
      - 0
      - 2
      - 0
      - 1
      - 1
      - 2
score_model:
  BASE_URL: https://api.exchangeratesapi.io/history
  FORECAST_PERIOD: 7
  NUM_LOOK_BACK_YRS: 2